//! End-to-end wide-aggregate test: a `count` policy whose in-window match set is
//! larger than `DistinctRows`'s hash-index promotion threshold, replayed through
//! a real `LocalTemporalEngine` and checked against the by-construction verdict.
//!
//! This is the integration-level complement to the `rows.rs` unit tests (which
//! exercise `DistinctRows` in isolation): it drives the *whole* path — lower →
//! aggregate evaluation → the relation-dedup machinery — at the production
//! `INDEX_THRESHOLD`, so the wide-relation (hash-index) path is exercised through
//! the engine, not just the container.
//!
//! ## Provenance
//!
//! The materialized fixtures under `fixtures/wide_count_k20/` were generated by
//! a wide-count workload generator with k = 20, then validated against the
//! reference interpreter using the pinned `ServiceSchema::defaults()`.
//!
//! ## Schema convention
//!
//! Lowered with `ServiceSchema::defaults()` (the **pinned** default) to match how
//! the reference computed `expected` — NOT the unpinned convention the external
//! corpus replay harness uses. The verdict is
//! known by construction, so this needs no second engine to compare against.

use dogwood_language::{
    Authorizer, Decision, LoweredPolicySet, PolicySchema, ServiceSchema, Validator,
};
use dogwood_local_engine::LocalTemporalEngine;

const SCHEMA: &str = include_str!("fixtures/wide_count_k20/schema.cedarschema");
const POLICY: &str = include_str!("fixtures/wide_count_k20/policy.dw");
const TRACE: &str = include_str!("fixtures/wide_count_k20/trace.log");
const EXPECTED: &str = include_str!("fixtures/wide_count_k20/expected.txt");

/// Lower the materialized `count`-policy under the pinned default schema, replay
/// its trace through a fresh `LocalTemporalEngine`, and require the per-timepoint
/// verdict stream to equal the by-construction reference. The trace holds 20
/// distinct in-window matches — past `DistinctRows`'s index-promotion threshold —
/// so the aggregate's dedup traverses the hash-index path end to end.
#[test]
fn wide_count_aggregate_agrees_with_construction() {
    let service = ServiceSchema::defaults();
    let policy_schema = PolicySchema::from_cedarschema_str(SCHEMA).expect("fixture schema parses");
    let lowered = LoweredPolicySet::from_str(POLICY, &service, &policy_schema)
        .expect("fixture policy lowers");
    assert!(
        Validator::new().validate(&lowered).validation_passed(),
        "fixture policy must type-check"
    );

    let events = dogwood_language::parse_trace(TRACE).expect("fixture trace parses");
    let mut auth = Authorizer::builder(lowered)
        .temporal_engine(LocalTemporalEngine::new())
        .build()
        .expect("authorizer builds over the local engine");

    // Reproduce the reference verdict-stream format: one line per decision-kind
    // (request) event, `@<ts> (time point <i>): <bool>`.
    let mut lines = Vec::new();
    for (i, e) in events.iter().enumerate() {
        if let Some(r) = auth.is_authorized(e) {
            lines.push(format!(
                "@{} (time point {i}): {}",
                e.timestamp(),
                r.decision() == Decision::Allow
            ));
        }
    }
    let got = lines.join("\n");

    // Compare on content, not line endings: EXPECTED is a checked-in fixture and
    // Git may deliver it with CRLF on Windows, whereas `got` is joined with '\n'.
    // Normalize both so the assertion is about the verdict stream, not the eol.
    let normalize = |s: &str| s.replace("\r\n", "\n");
    assert_eq!(
        normalize(got.trim_end()),
        normalize(EXPECTED.trim_end()),
        "local engine must reproduce the by-construction verdict for the wide count case"
    );

    // Sanity: exactly one Allow (the YES guard at time point 20), so the wide
    // count genuinely fired rather than the whole stream degenerating.
    let allows = got.lines().filter(|l| l.ends_with("true")).count();
    assert_eq!(allows, 1, "exactly the YES guard should allow");
}
